services:

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: facturx-nginx

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - frontend
      - backend

    networks:
      - facturx-network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: facturx-frontend

    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

    environment:
      - VITE_API_URL=

    depends_on:
      - backend

    networks:
      - facturx-network


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: facturx-backend

    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - facturx-network


  postgres:
    image: postgres:17

    container_name: facturx-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facturx

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d facturx"]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - facturx-network


volumes:
  postgres-data:


networks:
  facturx-network:
    driver: bridge
