name: Main CI Workflow

on:
  pull_request:

jobs:
  Job_1:
    name: Job_1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hello World
        run: |
          echo "hello world"
          pwd
          ls -la
